export const TEXTS = {
  app: {
    name: 'HernandezLab',
  },
  roles: {
    administrativo: 'Administrativo',
    recepcion: 'Recepción',
  },
  auth: {
    title: 'Iniciar sesión',
    subtitle: 'HernandezLab — sistema de gestión de laboratorio',
    emailLabel: 'Correo',
    passwordLabel: 'Contraseña',
    submit: 'Entrar',
    submitting: 'Ingresando...',
    logout: 'Cerrar sesión',
    loadingSession: 'Verificando sesión...',
    errors: {
      credenciales: 'Correo o contraseña incorrectos.',
      sinEmpleadoVinculado: 'Esta cuenta no está vinculada a ningún empleado del sistema.',
      generico: 'Ocurrió un error inesperado. Intenta de nuevo.',
    },
  },
  layout: {
    sidebarGroupPrincipal: 'Principal',
    sidebarGroupAdministracion: 'Administración',
    nav: {
      dashboard: 'Inicio',
      usuarios: 'Usuarios',
      sucursales: 'Sucursales',
      inventario: 'Inventario',
      solicitudes: 'Solicitudes',
      proveedores: 'Proveedores',
    },
  },
  sucursalSelector: {
    label: 'Sucursal activa',
    placeholder: 'Selecciona una sucursal',
  },
  comun: {
    proximamente: 'Este módulo se termina de construir en la siguiente fase.',
    activo: 'Activo',
    inactivo: 'Inactivo',
    acciones: 'Acciones',
    total: 'Total',
    guardando: 'Guardando...',
    eliminando: 'Eliminando...',
  },
  usuarios: {
    title: 'Usuarios',
    createButton: 'Crear usuario',
    editButton: 'Editar',
    deleteButton: 'Eliminar',
    empty: 'Aún no hay usuarios registrados.',
    table: {
      cedula: 'Cédula',
      nombre: 'Nombre',
      apellido: 'Apellido',
      cargo: 'Cargo',
      rol: 'Rol',
      sucursal: 'Sucursal',
      estado: 'Estado',
    },
    form: {
      createTitle: 'Crear usuario',
      editTitle: 'Editar usuario',
      cedulaLabel: 'Cédula',
      cedulaHelper: 'No se puede modificar luego de creado.',
      nombreLabel: 'Nombre',
      apellidoLabel: 'Apellido',
      cargoLabel: 'Cargo',
      rolLabel: 'Rol',
      sucursalLabel: 'Sucursal',
      estadoLabel: 'Usuario activo',
      loginNote:
        'Este formulario crea el registro del empleado. Para que pueda iniciar sesión, crea su cuenta en Authentication → Users del Dashboard de Supabase.',
      submitCreate: 'Crear',
      submitEdit: 'Guardar cambios',
      cancel: 'Cancelar',
    },
    confirmDelete: {
      title: 'Eliminar usuario',
      message: (nombreCompleto) =>
        `¿Seguro que deseas eliminar a ${nombreCompleto}? Esta acción no se puede deshacer.`,
      confirm: 'Eliminar',
      cancel: 'Cancelar',
    },
    errors: {
      generico: 'Ocurrió un error al guardar. Intenta de nuevo.',
      cedulaDuplicada: 'Ya existe un empleado con esa cédula.',
    },
  },
  sucursales: {
    title: 'Sucursales',
    createButton: 'Crear sucursal',
    editButton: 'Editar',
    deleteButton: 'Eliminar',
    empty: 'Aún no hay sucursales registradas.',
    table: {
      nombre: 'Nombre',
      direccion: 'Dirección',
      telefono: 'Teléfono',
      estado: 'Estado',
    },
    form: {
      createTitle: 'Crear sucursal',
      editTitle: 'Editar sucursal',
      nombreLabel: 'Nombre',
      direccionLabel: 'Dirección',
      telefonoLabel: 'Teléfono',
      estadoLabel: 'Sucursal activa',
      submitCreate: 'Crear',
      submitEdit: 'Guardar cambios',
      cancel: 'Cancelar',
    },
    confirmDelete: {
      title: 'Eliminar sucursal',
      message: (nombre) => `¿Seguro que deseas eliminar la sucursal "${nombre}"? Esta acción no se puede deshacer.`,
      confirm: 'Eliminar',
      cancel: 'Cancelar',
    },
    errors: {
      generico: 'Ocurrió un error al guardar. Intenta de nuevo.',
    },
  },
  proveedores: {
    title: 'Proveedores',
    createButton: 'Crear proveedor',
    editButton: 'Editar',
    deleteButton: 'Eliminar',
    empty: 'Aún no hay proveedores registrados.',
    table: {
      rif: 'RIF/Cédula',
      razonSocial: 'Razón social',
      contacto: 'Contacto',
      telefono: 'Teléfono',
    },
    form: {
      createTitle: 'Crear proveedor',
      editTitle: 'Editar proveedor',
      rifLabel: 'RIF/Cédula',
      razonSocialLabel: 'Razón social',
      contactoLabel: 'Persona de contacto',
      telefonoLabel: 'Teléfono',
      submitCreate: 'Crear',
      submitEdit: 'Guardar cambios',
      cancel: 'Cancelar',
    },
    confirmDelete: {
      title: 'Eliminar proveedor',
      message: (nombre) => `¿Seguro que deseas eliminar a "${nombre}"? Esta acción no se puede deshacer.`,
      confirm: 'Eliminar',
      cancel: 'Cancelar',
    },
    errors: {
      generico: 'Ocurrió un error al guardar. Intenta de nuevo.',
      rifDuplicado: 'Ya existe un proveedor con ese RIF/cédula.',
    },
  },
  inventario: {
    title: 'Inventario',
    createButton: 'Agregar ítem',
    editButton: 'Editar',
    deleteButton: 'Eliminar',
    empty: 'No hay ítems en esta categoría.',
    stockBajo: 'Stock bajo',
    sinProveedor: 'Sin proveedor',
    categorias: {
      insumos: 'Insumos',
      reactivos: 'Reactivos',
      mobiliario: 'Mobiliario',
      maquinaria: 'Maquinaria',
    },
    table: {
      codigo: 'Código',
      nombre: 'Nombre',
      stockActual: 'Stock actual',
      stockMinimo: 'Stock mínimo',
      fechaVencimiento: 'Vencimiento',
      lote: 'Lote',
      proveedor: 'Proveedor',
    },
    form: {
      createTitle: 'Agregar ítem',
      editTitle: 'Editar ítem',
      categoriaLabel: 'Categoría',
      codigoLabel: 'Código',
      nombreLabel: 'Nombre',
      stockActualLabel: 'Stock actual',
      stockMinimoLabel: 'Stock mínimo',
      fechaVencimientoLabel: 'Fecha de vencimiento',
      loteLabel: 'Lote',
      proveedorLabel: 'Proveedor',
      sinProveedorOption: 'Sin proveedor',
      submitCreate: 'Crear',
      submitEdit: 'Guardar cambios',
      cancel: 'Cancelar',
    },
    confirmDelete: {
      title: 'Eliminar ítem',
      message: (nombre) => `¿Seguro que deseas eliminar "${nombre}" del inventario? Esta acción no se puede deshacer.`,
      confirm: 'Eliminar',
      cancel: 'Cancelar',
    },
    errors: {
      generico: 'Ocurrió un error al guardar. Intenta de nuevo.',
      codigoDuplicado: 'Ya existe un ítem con ese código en esta sucursal.',
    },
  },
  solicitudes: {
    title: 'Solicitudes',
    createButton: 'Nueva solicitud',
    empty: 'Aún no hay solicitudes registradas.',
    table: {
      paciente: 'Paciente',
      fecha: 'Fecha',
      examenes: 'Exámenes',
      estado: 'Estado',
      total: 'Total a pagar',
    },
    estados: {
      pendiente: 'Pendiente',
      en_proceso: 'En proceso',
      entregado: 'Entregado',
    },
    form: {
      createTitle: 'Nueva solicitud',
      pacienteSectionTitle: 'Datos del paciente',
      cedulaLabel: 'Cédula',
      nombreLabel: 'Nombre',
      apellidoLabel: 'Apellido',
      fechaNacimientoLabel: 'Fecha de nacimiento',
      generoLabel: 'Género',
      pacienteExistenteNota: 'Paciente ya registrado — datos cargados automáticamente.',
      examenesSectionTitle: 'Exámenes solicitados',
      examenesLabel: 'Selecciona los exámenes',
      consumoTitle: 'Insumos/reactivos que se descontarán del inventario',
      consumoVacio: 'Este examen no tiene insumos/reactivos asociados.',
      totalLabel: 'Total a pagar',
      submitCreate: 'Registrar solicitud',
      cancel: 'Cancelar',
    },
    errors: {
      generico: 'Ocurrió un error al registrar la solicitud. Intenta de nuevo.',
      stockInsuficiente: 'No hay stock suficiente para completar esta solicitud.',
      seleccionaExamen: 'Selecciona al menos un examen.',
    },
  },
};
